import './globals.css'
import { Montserrat } from 'next/font/google'
// Components
import Navbar from './components/navbar'
import Footer from './components/footer'
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Smart Intro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
